<?xml version="1.0"?>
<robot name="sensor_stereolabs_zed" xmlns:xacro="http://ros.org/wiki/xacro">
  
  <!-- Xacro properties -->
  <xacro:property name="M_SCALE" value="0.001"/>
  <xacro:property name="optical_y_offset" value="0.06" />

  <!-- Parameterised in part by the values in turtlebot_properties.urdf.xacro -->
  <xacro:macro name="sensor_stereolabs_zed" params="parent">
    
    <joint name="stereo_camera_left_joint" type="fixed">
      <origin xyz="${cam_px} ${cam_py} ${cam_pz}" 
              rpy="${cam_or} ${cam_op} ${cam_oy}"/>
      <parent link="${parent}"/>
      <child link="stereo_camera_left_frame" />
    </joint>
    <link name="stereo_camera_left_frame"/>

    <joint name="camera_left_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="stereo_camera_left_frame" />
      <child link="stereo_camera_left_optical_frame" />
    </joint>
    <link name="stereo_camera_left_optical_frame"/>

    <joint name="_camera_joint" type="fixed">
      <origin xyz="0 ${-optical_y_offset} 0" 
              rpy="0 0 0"/>
      <parent link="stereo_camera_left_frame"/>
      <child link="stereo_camera_link"/>
    </joint>
    <link name="stereo_camera_link">
      <visual>
        <origin xyz="-0.01 0 0" rpy="${-M_PI/2} -${M_PI} ${-M_PI/2}"/>
        <geometry>
          <mesh filename="package://myzharbot_description/meshes/sensors/asus_xtion_pro_live.dae" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
        <box size="0.0730 0.2760 0.0720"/>
      </geometry>
      </collision>
      <inertial>
        <mass value="0.170" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001152600" ixy="0.0" ixz="0.0"
                 iyy="0.000148934" iyz="0.0"
                 izz="0.001154654" />
      </inertial>
    </link>

    <joint name="stereo_camera_right_joint" type="fixed">
      <origin xyz="0 ${-2*optical_y_offset} 0" rpy="0 0 0" />
      <parent link="stereo_camera_left_frame" />
      <child link="stereo_camera_right_frame" />
    </joint>
    <link name="stereo_camera_right_frame"/>

    <joint name="camera_right_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="stereo_camera_right_frame" />
      <child link="stereo_camera_right_optical_frame" />
    </joint>
    <link name="stereo_camera_right_optical_frame"/>

  </xacro:macro>
</robot>
